
require("plugins.colorscheme")
require("plugins.lualine")
require("plugins.bufferline")

vim.schedule(function()
  require("plugins.telescope")
  require("plugins.treesitter")
  require("plugins.cmp")
  require("plugins.lsp")
  require("plugins.conform")
  require("plugins.pairs")
  require("plugins.autotag")
  require("plugins.surround")
  require("plugins.supermaven")
  require("plugins.dap")
  require("plugins.flutter")
  require("plugins.which_key")
  require("plugins.ts_comments")
  require("plugins.hipatterns")
  require("plugins.oil")
  require("plugins.grug_far")
  require("plugins.inc_rename")
  require("plugins.inline_diagnostic")
end)
